version: 0.2

phases:
  install:
    commands:
      - echo "I'm a little teapot."
  pre_build:
    commands:
      - echo "Get to the choppa!"
  build:
    commands:
      - echo "Hello Darkness, my old friend..."
      - go build -o $CODEBUILD_SRC_DIR/app
  post_build:
    commands:
      - echo "Darth Vader seduced and murdered your father."
      - go test
artifacts:
  files:
   - $CODEBUILD_SRC_DIR/app
